#ifndef INTERSECTION_H
#define INTERSECTION_H
void intersec_tr_cir(
        double& x0,
        double& y0,
        double& rad,
        double& x1,
        double& y1,
        double& x2,
        double& y2,
        double& x3,
        double& y3);
void intersec_cir_tr(
        double& x0,
        double& y0,
        double& rad,
        double& x1,
        double& y1,
        double& x2,
        double& y2,
        double& x3,
        double& y3);
#endif